# Generated by Django 5.1.5 on 2025-02-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bio',
            new_name='about_me',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorite_cuisine',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('OWNER', 'Restaurant Owner'), ('ADMIN', 'Website Admin')], max_length=10),
        ),
    ]
