# Generated by Django 5.1.5 on 2025-02-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menudesign',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
